[intrinsics] Use the `__ARM_NEON` macro for the Advanced SIMD support
ARM-software/acle pull request #16
Opened 2021-07-19 12:02 UTC by MattPD

Fixes #15: Advanced SIMD support is available if the `__ARM_NEON` macro is predefined, <https://developer.arm.com/documentation/101028/0012/13--Advanced-SIMD--Neon--intrinsics>.

2021-07-19 12:10 UTC, fpetrogalli commented
@MattPD - thank you! I forgot to mention that the `main` branch is always tracking the latest release (yeah, buggy in this specific case), and that PR should be submitted against `next-release`. It is specified in the main `README` doc, maybe I should try to make it more visible.

CI is unhappy about your code because the specs you have modified are generated out of the DB in https://github.com/ARM-software/acle/blob/main/tools/intrinsic_db/advsimd.csv. The text should be modified in there too (line 16 of the CSV file).

2021-07-19 14:39 UTC, fpetrogalli requested changes
Please modify also the corresponding line in `adv_simd.csv` (see `tools/intrinsics_db`).

Francesco

2021-07-19 16:48 UTC, MattPD commented
Thanks, will do!

(Closing this and opening a new one, switching branches.)

2021-07-19 16:48 UTC, closed without merging

2021-07-22 07:30 UTC, fpetrogalli commented
Resolved by #17