Add ACLE macros for FEAT_PAuth_LR
ARM-software/acle pull request #292
Opened 2024-01-24 16:29 UTC by pratlucas

The Armv9.5a introduces the FEAT_PAuth_LR extension, adding an enhancement
to the Pointer Authentication extension where the value of PC is used as
a diversifier when signing pointers.

This updates the ACLE to support the extension by the introduction of a
new feature marcro and the addition of a new possible value to the
existing `__ARM_FEATURE_PAC_DEFAULT` macro.

2024-01-29 11:48 UTC, vhscampos requested changes
In addition to my inline comments, there's a typo in the commit message: "marcro"

2024-01-29 11:48 UTC, vhscampos commented on main/acle.md
> +  for the Armv9.5a's PAC Enhancements.
For consistency please add a hyphen to v9.5a. "v9.5-a"

2024-01-29 11:48 UTC, vhscampos commented on main/acle.md
> +`__ARM_FEATURE_PAUTH_LR` is defined to 1 if Armv9.5a enhancements to the
Same here (hyphen)

2024-01-29 11:48 UTC, vhscampos commented on main/acle.md
> +| [`__ARM_FEATURE_PAUTH_LR`](#pointer-authentication)                                                                                                     | Armv9.5a Enhancements to Pointer Authentica
Same (hyphen)

2024-01-29 13:46 UTC, pratlucas commented
Thank's @vhscampos ! I've fixed the items from the comments and the typo in the PR description. I'll make sure it's also fixed on the commit message when the change is merged.

2024-01-29 13:48 UTC, vhscampos approved these changes

2024-01-29 13:48 UTC, vhscampos commented
LGTM. Thank you!

2024-01-29 14:47 UTC, merged

2024-01-29 14:49 UTC, vhscampos commented
@all-contributors please add @pratlucas for code

2024-03-25 16:53 UTC, sallyarmneale commented on main/acle.md
> +  for the Armv9.5-A's PAC Enhancements.
Armv9.5-A's PAC

Remove the possessive apostrophe

2024-03-25 16:53 UTC, sallyarmneale reviewed
1 minor change